# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: start doccer
    init: |
      npm i doccer/
    command: |
      git config pull.rebase false
      npm run --prefix doccer/ start

image:
  file: .gitpod.dockerfile

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
   - port: 3000
     onOpen: open-preview
